name: CMake

on: [push]


jobs:
  # Do the G++-14 test!
  build_gnu14:
    name: Test build with g++-14
    runs-on: ubuntu-24.04
    env:
      CXX: g++-14

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
       submodules: recursive
    - name: Conduct CMake test
      uses: HyperHDG/actions@cmake
      with:
        cxx_compiler: ${{env.CXX}}

  # Do the Clang++-19 test!
  build_clang10:
    name: Test build with clang++-19
    runs-on: ubuntu-24.04
    env:
      CXX: clang++-19

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
       submodules: recursive
    - name: Conduct CMake test
      uses: HyperHDG/actions@cmake
      with:
        cxx_compiler: ${{env.CXX}}
