name: Doxygen

# Act only if a 'push' occurred.
on: push

# In that case do the job 'make_and_deploy_doxygen'
jobs:
  make_and_deploy_doxygen:
    runs-on: ubuntu-latest
    # which needs the following steps to be executed:
    steps:
      # 1. Checkout current branch of GitHub repository.
      - name: Checkout current branch
        uses: actions/checkout@v2
      # 2. Install doxygen and its auxiliary components.
      - name: Install doxygen components
        run: sudo apt-get update; sudo apt-get install -y doxygen graphviz
      # 3. Create the doxygen pages.
      - name: Create the doxygen
        run: |
          mkdir build
          cd build
          cmake -DBUILD_DOC:BOOL=ON ..
          make doxygen
